# Generated by Django 5.2 on 2025-05-04 10:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date of creation')),
                ('life_duration', models.DurationField(default=datetime.timedelta(0), verbose_name='life duration')),
                ('user_owner', models.CharField(verbose_name='pixel owner')),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_date', models.DateField(verbose_name='date of opening')),
                ('ip', models.GenericIPAddressField(verbose_name='receiver ip')),
                ('pixel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixelspy.pixel')),
            ],
        ),
    ]
