# Generated by Django 5.2.1 on 2025-05-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelspy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='display_url',
            field=models.URLField(default=None, verbose_name='pixel display url'),
            preserve_default=False,
        ),
    ]
