# Generated by Django 5.2.1 on 2025-05-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelspy', '0002_pixel_display_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='request_header',
            field=models.CharField(default=None, verbose_name='request header metadata'),
            preserve_default=False,
        ),
    ]
