# Generated by Django 5.2.1 on 2025-05-31 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelspy', '0005_alter_pixel_user_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pixel',
            old_name='life_duration',
            new_name='lifetime',
        ),
        migrations.RenameField(
            model_name='pixel',
            old_name='user_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='pixel',
            old_name='display_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='opened_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='request_header',
            new_name='header',
        ),
    ]
