# Generated by Django 5.2.1 on 2025-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelspy', '0006_rename_life_duration_pixel_lifetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pixel',
            old_name='creation_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='pixel',
            name='description',
            field=models.CharField(default='', verbose_name='pixel user description'),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='url',
            field=models.URLField(verbose_name='pixel display url'),
        ),
    ]
