# Generated by Django 5.2.1 on 2025-06-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelspy', '0008_alter_tracker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='description',
            field=models.CharField(default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='url',
            field=models.URLField(verbose_name='display url'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='header',
            field=models.CharField(default='', verbose_name='request metadata'),
        ),
    ]
