# Generated by Django 5.2.1 on 2025-06-29 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelspy', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_lifetime',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='default pixel life duration'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='header',
            field=models.CharField(default='', verbose_name='request header'),
        ),
    ]
