# Generated by Django 5.2.1 on 2025-06-29 17:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelspy', '0011_profile_default_lifetime_alter_tracker_header'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_lifetime',
            field=models.DurationField(default=datetime.timedelta(days=14), verbose_name='default pixel life duration'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hide_expired',
            field=models.BooleanField(default=True, verbose_name='hide expired pixels'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
