# Generated by Django 5.2.1 on 2025-06-29 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelspy', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_lifetime',
            field=models.DurationField(default=datetime.timedelta(days=14), max_length=3153686399, verbose_name='default pixel life duration'),
        ),
    ]
