# Generated by Django 5.2.1 on 2025-06-29 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelspy', '0014_alter_profile_default_lifetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_lifetime',
            field=models.DurationField(default=datetime.timedelta(days=14), verbose_name='default pixel life duration'),
        ),
    ]
